apiVersion: v1
kind: Service
metadata:
  name: api-sales-gateway
  labels:
    run: api-sales-gateway
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http-ws
  selector:
    run: api-sales-gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-sales-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: api-sales-gateway
    spec:
      containers:
      - name: api-sales-gateway
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        image: nebulaepyxis/salesgateway:1.0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          # an http probe
          httpGet:
            path: /api/sales-gateway/graphiql
            port: 3000
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 5
          timeoutSeconds: 10
        env:
        - name: NODE_ENV
          value: production
        # GRAPHQL CONGIF      
        - name: GRAPHQL_END_POINT_PORT
          value: '3000'
        - name: GRAPHQL_END_POINT_HOST
          value: localhost
        - name: GRAPHQL_HTTP_END_POINT
          value: /api/sales-gateway/graphql/http
        - name: GRAPHIQL_HTTP_END_POINT
          value: /api/sales-gateway/graphiql
        - name: GRAPHQL_WS_END_POINT
          value: /api/sales-gateway/graphql/ws
        # APOLLO ENGINE CONFIG
        - name: APOLLO_ENGINE_API_KEY
          valueFrom:
            secretKeyRef:
              name: apollo
              key: engine_api_key
        - name: APOLLO_ENGINE_LOG_LEVEL
          value: WARN         
        # GCLOUD PUB_SUB CONGIF       
        - name: BROKER_TYPE
          value: PUBSUB         
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json  
        - name: GCLOUD_PROJECT_ID
          value: nebulae-pyxis  
        - name: GATEWAY_REPLIES_TOPIC
          value: sales-gateway-replies
        - name: GATEWAY_REPLIES_TOPIC_SUBSCRIPTION
          value: sales-gateway-replies
        - name: GATEWAY_EVENTS_TOPIC
          value: events
        - name: GATEWAY_EVENTS_TOPIC_SUBSCRIPTION
          value: events-sales-gateway
        - name: GATEWAY_MATERIALIZED_VIEW_UPDATES_TOPIC
          value: sales-gateway-materialized-view-updates
        - name: GATEWAY_MATERIALIZED_VIEW_UPDATES_TOPIC_SUBSCRIPTION
          value: sales-gateway-materialized-view-updates-sales-gateway
        - name: REPLY_TIMEOUT
          value: '2000'
        # JWT CONGIF        
        - name: JWT_PUBLIC_KEY
          value: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6mv0ByMprlVOd2tzyw/+BxOylLOTG5+oLFgaCiQu3RSIoVyDXtK9d2+kSmP2qsDE+wqVFEdpw2HrUXB8vhjUpu0CluzIw4m5v6l6ExHqyQHBWTCrX4Aynb3eQIWDm1B5Z592XYBLC+ZMDCDkUeiy7R4rGZnG7BPieAGP7KpO23Yc3YVe16Xkwewp3KOgMwch3uyjLVLu386qAeRfEd6yoMYjt+n5dJ5Lv9ZE+vod+BXOrlbmar3GLnE+x+c07YQfAk1jG2WRucN2wqmBKvygRz/Z50jMEclUjddH2wiXbBp9g83MDSQna93tOxlnhRmCTkzsRZqSRVb7HzjASIbfFQIDAQAB\n-----END PUBLIC KEY-----          
              
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
