apiVersion: v1
kind: Service
metadata:
  name: api-sales-gateway
  labels:
    run: api-sales-gateway
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http-ws
  selector:
    run: api-sales-gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-sales-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: api-sales-gateway
    spec:
      containers:
      - name: api-sales-gateway
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        image: nebulaepyxis/salesgateway:1.0.11
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          # an http probe
          httpGet:
            path: /api/sales-gateway/graphql/liveness
            port: 3000
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources:
          requests:
            cpu: "50m"
        env:
        - name: NODE_ENV
          value: production
        # GRAPHQL CONGIF      
        - name: GRAPHQL_END_POINT_PORT
          value: '3000'
        - name: GRAPHQL_END_POINT_HOST
          value: localhost
        - name: GRAPHQL_HTTP_END_POINT
          value: /api/sales-gateway/graphql/http
        - name: GRAPHIQL_HTTP_END_POINT
          value: /api/sales-gateway/graphql/http
        - name: GRAPHQL_LIVENESS_HTTP_END_POINT
          value: /api/sales-gateway/graphql/liveness
        - name: GRAPHQL_WS_END_POINT
          value: /api/sales-gateway/graphql/ws
        # APOLLO ENGINE CONFIG
        - name: APOLLO_ENGINE_API_KEY
          valueFrom:
            secretKeyRef:
              name: apollo
              key: engine_api_key
        - name: APOLLO_ENGINE_LOG_LEVEL
          value: WARN         
        # GCLOUD PUB_SUB CONGIF       
        - name: BROKER_TYPE
          value: PUBSUB         
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json  
        - name: GCLOUD_PROJECT_ID
          value: nebulae-pyxis  
        - name: GATEWAY_REPLIES_TOPIC
          value: sales-gateway-replies
        - name: GATEWAY_REPLIES_TOPIC_SUBSCRIPTION
          value: sales-gateway-replies
        - name: GATEWAY_EVENTS_TOPIC
          value: events
        - name: GATEWAY_EVENTS_TOPIC_SUBSCRIPTION
          value: events-sales-gateway
        - name: GATEWAY_MATERIALIZED_VIEW_UPDATES_TOPIC
          value: sales-gateway-materialized-view-updates
        - name: GATEWAY_MATERIALIZED_VIEW_UPDATES_TOPIC_SUBSCRIPTION
          value: sales-gateway-materialized-view-updates-sales-gateway
        - name: REPLY_TIMEOUT
          value: '2000'
        # JWT CONGIF        
        - name: JWT_PUBLIC_KEY
          value: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsQBquKLlhsh1IObDD+KP45iBjelCjiF4mxLEqFkwHpGBZZckjQRPeXCc/z/nhJd47VnmyFiRFNGifpIraneLJYz1XrJ6B1fqGyfLf4mFErIffk4lQpCVUeaW/QyMFdwHN2jhe3S7yWx3gaD3ZKOX7egqZhD5gTEaYldhJX26kmJJHvuuG8t/etjxeNLy0GhLi2E1WhP6M9NGtVKS/02P16CJPr0SFQVXOUdgi5kQUS74rHB/CzEjQNziO2v2BnZVDMbKckSpzWl/zcu388/81hIlLvYpO+NtseioIQYB9sHBoaEs2cKwNEUEGKzcDezfR8fdSoGJ2wYQBnhQTMH0ewIDAQAB\n-----END PUBLIC KEY-----          
              
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
